name = "hono-restful"
main = "src/index.ts"
compatibility_date = "2026-02-12"
routes = [
  { pattern = "todo.w3ctech.dev", custom_domain = true, zone_name = "w3ctech.dev" }
]

[vars]
DB_DRIVER = "d1"

[[d1_databases]]
binding = "DB"
database_name = "todo-db"
database_id = "2346c681-1380-4b2e-9de2-4fc08b97340d"
migrations_dir = "migrations"
